// DESIGN PHASE ONLY — mock data for the Verification page UI.
// Phase 2 will replace this with real Firestore queries
// (regular_user collection where verificationStatus == 'pending').

const PLACEHOLDER = (text, bg = '#e2e8f0', fg = '#475569') =>
  `https://placehold.co/480x300/${bg.slice(1)}/${fg.slice(1)}?text=${encodeURIComponent(text)}`

export const MOCK_VERIFICATIONS = [
  {
    key: 'v-001',
    uid: 'mock-uid-001',
    fullName: 'Juan Dela Cruz',
    email: 'juan.delacruz@gmail.com',
    idType: 'PhilID / National ID',
    livenessPassed: true,
    enrolledAt: 'Aug 28, 2026 · 3:10 PM',
    submittedAt: 'Aug 30, 2026 · 10:24 AM',
    verificationStatus: 'pending',
    images: {
      front: PLACEHOLDER('ID Front — PhilID', '#dbeafe', '#1e40af'),
      back: PLACEHOLDER('ID Back — PhilID', '#e0e7ff', '#3730a3'),
      enrollmentSelfie: PLACEHOLDER('Enrollment Selfie', '#dcfce7', '#166534'),
      loginSelfie: PLACEHOLDER('Login Selfie', '#fef9c3', '#854d0e'),
    },
    rejectionReason: null,
  },
  {
    key: 'v-002',
    uid: 'mock-uid-002',
    fullName: 'Maria Santos',
    email: 'maria.santos@yahoo.com',
    idType: "Driver's License",
    livenessPassed: true,
    enrolledAt: 'Aug 27, 2026 · 6:05 PM',
    submittedAt: 'Aug 29, 2026 · 4:51 PM',
    verificationStatus: 'pending',
    images: {
      front: PLACEHOLDER('ID Front — Driver’s License', '#dbeafe', '#1e40af'),
      back: PLACEHOLDER('ID Back — Driver’s License', '#e0e7ff', '#3730a3'),
      enrollmentSelfie: PLACEHOLDER('Enrollment Selfie', '#dcfce7', '#166534'),
      loginSelfie: PLACEHOLDER('Login Selfie', '#fef9c3', '#854d0e'),
    },
    rejectionReason: null,
  },
  {
    key: 'v-003',
    uid: 'mock-uid-003',
    fullName: 'Pedro Ramirez',
    email: 'pedro.ramirez@outlook.com',
    idType: 'Passport',
    livenessPassed: false,
    enrolledAt: 'Aug 26, 2026 · 7:30 PM',
    submittedAt: 'Aug 29, 2026 · 9:12 AM',
    verificationStatus: 'pending',
    images: {
      front: PLACEHOLDER('ID Front — Passport', '#dbeafe', '#1e40af'),
      back: PLACEHOLDER('ID Back — Passport', '#e0e7ff', '#3730a3'),
      enrollmentSelfie: PLACEHOLDER('Enrollment Selfie', '#dcfce7', '#166534'),
      loginSelfie: PLACEHOLDER('Login Selfie', '#fef9c3', '#854d0e'),
    },
    rejectionReason: null,
  },
  {
    key: 'v-004',
    uid: 'mock-uid-004',
    fullName: 'Ana Lopez',
    email: 'ana.lopez@gmail.com',
    idType: 'UMID',
    livenessPassed: true,
    enrolledAt: 'Aug 25, 2026 · 10:02 AM',
    submittedAt: 'Aug 27, 2026 · 2:08 PM',
    verificationStatus: 'verified',
    images: {
      front: PLACEHOLDER('ID Front — UMID', '#dbeafe', '#1e40af'),
      back: PLACEHOLDER('ID Back — UMID', '#e0e7ff', '#3730a3'),
      enrollmentSelfie: PLACEHOLDER('Enrollment Selfie', '#dcfce7', '#166534'),
      loginSelfie: PLACEHOLDER('Login Selfie', '#fef9c3', '#854d0e'),
    },
    rejectionReason: null,
  },
  {
    key: 'v-005',
    uid: 'mock-uid-005',
    fullName: 'Carlo Mendoza',
    email: 'carlo.mendoza@gmail.com',
    idType: 'Postal ID',
    livenessPassed: true,
    enrolledAt: 'Aug 24, 2026 · 5:44 PM',
    submittedAt: 'Aug 26, 2026 · 11:40 AM',
    verificationStatus: 'verified',
    images: {
      front: PLACEHOLDER('ID Front — Postal ID', '#dbeafe', '#1e40af'),
      back: PLACEHOLDER('ID Back — Postal ID', '#e0e7ff', '#3730a3'),
      enrollmentSelfie: PLACEHOLDER('Enrollment Selfie', '#dcfce7', '#166534'),
      loginSelfie: PLACEHOLDER('Login Selfie', '#fef9c3', '#854d0e'),
    },
    rejectionReason: null,
  },
  {
    key: 'v-006',
    uid: 'mock-uid-006',
    fullName: 'Grace Villanueva',
    email: 'grace.villanueva@gmail.com',
    idType: 'PhilHealth ID',
    livenessPassed: false,
    enrolledAt: 'Aug 23, 2026 · 12:20 PM',
    submittedAt: 'Aug 25, 2026 · 3:33 PM',
    verificationStatus: 'rejected',
    images: {
      front: PLACEHOLDER('ID Front — PhilHealth', '#dbeafe', '#1e40af'),
      back: PLACEHOLDER('ID Back — PhilHealth', '#e0e7ff', '#3730a3'),
      enrollmentSelfie: PLACEHOLDER('Enrollment Selfie', '#dcfce7', '#166534'),
      loginSelfie: PLACEHOLDER('Login Selfie', '#fef9c3', '#854d0e'),
    },
    rejectionReason: 'Selfie does not match the face on the submitted ID.',
  },
  {
    key: 'v-007',
    uid: 'mock-uid-007',
    fullName: 'Jose Rizal Aquino',
    email: 'jose.aquino@gmail.com',
    idType: null,
    livenessPassed: true,
    enrolledAt: 'Aug 31, 2026 · 8:15 AM',
    submittedAt: null,
    verificationStatus: 'awaiting_id',
    images: {
      front: null,
      back: null,
      enrollmentSelfie: PLACEHOLDER('Enrollment Selfie', '#dcfce7', '#166534'),
      loginSelfie: null,
    },
    rejectionReason: null,
  },
  {
    key: 'v-008',
    uid: 'mock-uid-008',
    fullName: 'Liza Bacaltos',
    email: 'liza.bacaltos@yahoo.com',
    idType: null,
    livenessPassed: true,
    enrolledAt: 'Aug 31, 2026 · 1:42 PM',
    submittedAt: null,
    verificationStatus: 'awaiting_id',
    images: {
      front: null,
      back: null,
      enrollmentSelfie: PLACEHOLDER('Enrollment Selfie', '#dcfce7', '#166534'),
      loginSelfie: null,
    },
    rejectionReason: null,
  },
]